title: |md
  # Binge Mate Services
| {near: top-center}

classes: {
  dev link: {
    style.stroke: "#30e81c"
  }
  prod link: {
    style.stroke: "#4287f5"
  }
  user link: {
    style.stroke: "#54bd44"
  }
  admin link: {
    style.stroke: "#f54242"
  }
}

cloudflare: Cloudflare {
  icon: https://seeklogo.com/images/C/cloudflare-logo-6B7D159387-seeklogo.com.png
  # shape: image
}

user: Utilisateur {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F365-user.svg
}

admin: Administrateur {
  shape: image
  icon: https://cdn0.iconfinder.com/data/icons/business-startup-10/50/76-512.png
}

scaleway: Scaleway {
  icon: https://cdn.icon-icons.com/icons2/2407/PNG/512/scaleway_icon_146103.png
  object_storage: Object Storage {
    icon: https://cdn1.iconfinder.com/data/icons/carbon-design-system-vol-8/32/volume--block-storage-256.png
    # shape: image
  }
  registry: Registry {
    icon: https://cdn4.iconfinder.com/data/icons/big-data/512/registry-256.png
    # shape: image
  }
}

github: Github {
  icon: https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-github-512.png
  github_action: Github Action {
    icon: https://seeklogo.com/images/G/github-actions-logo-031704BDC6-seeklogo.com.png
  }
  dependabot: Dependabot {
    icon: https://seeklogo.com/images/D/dependabot-logo-A0BA60FE2D-seeklogo.com.png
  }
}

tmdb: TMDB API {
  icon: https://pbs.twimg.com/profile_images/1243623122089041920/gVZIvphd_400x400.jpg
  # shape: image
}

stripe: Stripe {
  icon: https://play-lh.googleusercontent.com/2PS6w7uBztfuMys5fgodNkTwTOE6bLVB2cJYbu5GHlARAK36FzO5bUfMDP9cEJk__cE
  # shape: image
}

snyk: Snyke {
  icon: https://seeklogo.com/images/S/snyk-logo-77A649EC07-seeklogo.com.png?v=637937476260000000
}

kubernetes_cluster: Kubernetes Cluster {
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg

  auth: Identity Access Management {
    keycloak: Keycloak {
      icon: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png
      shape: image
    }

    db: BDD {
      shape: image
      icon: https://cdn1.iconfinder.com/data/icons/soleicons-fill-vol-1/64/postgres_database_server_relational_dbms_sql-512.png
    }
    keycloak -> db
  }

  api_manager: API Manager {
    icon: https://avatars.githubusercontent.com/u/12655666?s=200&v=4

    api_gateway: API Gateway {
      # shape: image
      icon: https://cdn1.iconfinder.com/data/icons/carbon-design-system-vol-4/32/gateway--api-512.png

      content: "" {
        label: |md
          - Authentication
          - Authorization
          - Rate Limiting
          - Caching
          - Logging
          - Metrics
          - Tracing
          - Circuit Breaker
          - Health Check
        |
      }
    }

    admin_api: Admin API {
      # shape: image
      icon: https://cdn1.iconfinder.com/data/icons/carbon-design-system-vol-2/32/api-512.png
    }

    portail: Portail {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/audit-3/512/18_Analysis_Report_Data_Web_Portal_Computing-512.png
    }

    console: Console {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/feather-5/24/terminal-512.png
    }

    mongo: MongoDB {
      shape: image
      icon: https://icons.terrastruct.com/dev%2Fmongodb.svg
    }

    elasticsearch: Elasticsearch {
      shape: image
      icon: https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/elasticsearch-512.png
    }

    api_gateway -> mongo
    api_gateway -> Elasticsearch
    admin_api -> mongo
    admin_api -> Elasticsearch
    portail -> mongo
    console -> admin_api
  }

  api_manager.api_gateway -> auth
  api_manager.admin_api -> auth

  system: System WorkSpace {
    rancher: Rancher Stack {
      icon: https://media.trustradius.com/product-logos/pJ/jl/0QRDLLI2NBM6.PNG
      shape: image
    }

    rancher_console: Rancher Console {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/feather-5/24/terminal-512.png
    }

    devops: DevOps {
      argocd: ArgoCD Stack {
        icon: https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png
        shape: image
      }
    }

    monitoring: Monitoring {
      grafana: {
        shape: image
        icon: https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/grafana-512.png
      }

      prometheus: Prometheus Operator {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1200px-Prometheus_software_logo.svg.png
        shape: image
      }
      kube_state_metrics: Kube State Metrics {
        icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
        shape: image
      }
      node_exporter: Node Exporter {
        icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
        shape: image
      }
      alertmanager: Alert Manager {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1200px-Prometheus_software_logo.svg.png
        shape: image
      }
      grafana -> prometheus
      kube_state_metrics -> prometheus
      node_exporter -> prometheus
      grafana <- alertmanager
    }
  }

  bingemate_workspace: Binge Mate WorkSpace {
    icon: https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-logo-design-creative-idea-logo-elements-2.png

    prod: Production Platform {
      keycloak-service: Keycloak Service {
        icon: https://seeklogo.com/images/G/go-logo-046185B647-seeklogo.com.png
        style.multiple: true
      }

      payment-service: Payment Service {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/NestJS.svg/1200px-NestJS.svg.png
        style.multiple: true
      }

      watch-service: Watch Service {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/NestJS.svg/1200px-NestJS.svg.png
        style.multiple: true
      }

      messaging-service: Messaging Service {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/NestJS.svg/1200px-NestJS.svg.png
        style.multiple: true
      }

      
      user-service: User Service {
        icon: https://seeklogo.com/images/Q/quarkus-logo-C9F006782E-seeklogo.com.png
        style.multiple: true
      }
      
      calendar-service: Calendar Service {
        icon: https://seeklogo.com/images/G/go-logo-046185B647-seeklogo.com.png
        style.multiple: true
      }
      
      media-service: Media Service {
        icon: https://seeklogo.com/images/G/go-logo-046185B647-seeklogo.com.png
        style.multiple: true
      }

      media-indexer: Media Indexer {
        icon: https://seeklogo.com/images/G/go-logo-046185B647-seeklogo.com.png
        style.multiple: true

        ffmpeg: "" {
          shape: image
          icon: https://seeklogo.com/images/F/ffmpeg-logo-188901058C-seeklogo.com.png
        }
      }
      streaming-service: Streaming Service {
        icon: https://seeklogo.com/images/G/go-logo-046185B647-seeklogo.com.png
        style.multiple: true
      }

      bingemate-web: Frontend {
        icon: https://seeklogo.com/images/A/angular-logo-B76B1CDE98-seeklogo.com.png
        style.multiple: true
      }

      bingemate-db: BDD {
        icon: https://seeklogo.com/images/P/postgresql-logo-5309879B58-seeklogo.com.png
        shape: cylinder
      }

      media-redis: Redis {
        icon: https://cdn4.iconfinder.com/data/icons/redis-2/1451/Untitled-2-512.png
        style.multiple: true
      }

      bingemate-storage: Storage {
        shape: page
        style.multiple: true
      }

      watch-service -> bingemate-db
      media-indexer -> bingemate-db
      media-service -> bingemate-db
      user-service -> bingemate-db
      calendar-service -> bingemate-db
      messaging-service -> bingemate-db
      payment-service -> bingemate-db

      media-service -> media-redis
      media-indexer -> media-redis
      calendar-service -> media-redis

      payment-service -> keycloak-service

      media-indexer -> bingemate-storage
      streaming-service -> bingemate-storage
    }
  }

  system.devops -> bingemate_workspace.prod: {
    class: prod link
  }

  api_manager.api_gateway -> bingemate_workspace.prod: {
    class: prod link
  }

  system.monitoring -> bingemate_workspace
  # system.monitoring -> api_manager

  bingemate_workspace -> auth
}

kubernetes_cluster -> scaleway.registry
kubernetes_cluster.system.devops -> github
kubernetes_cluster.bingemate_workspace.prod -> scaleway.object_storage
kubernetes_cluster.bingemate_workspace.prod -> tmdb
kubernetes_cluster.bingemate_workspace.prod -> stripe
github -> registry

admin -> cloudflare: {
  class: admin link
}
user -> cloudflare: {
  class: user link
}

cloudflare -> kubernetes_cluster.api_manager.console: {
  class: admin link
}
cloudflare -> kubernetes_cluster.system.rancher_console: {
  class: admin link
}
cloudflare -> kubernetes_cluster.system.monitoring.grafana: {
  class: admin link
}
cloudflare -> kubernetes_cluster.system.devops: {
  class: admin link
}
cloudflare -> kubernetes_cluster.auth: {
  class: admin link
}

cloudflare -> kubernetes_cluster.api_manager.portail: {
  class: user link
}
cloudflare -> kubernetes_cluster.api_manager.api_gateway: {
  class: user link
}
cloudflare -> kubernetes_cluster.auth: {
  class: user link
}

cloudflare -> kubernetes_cluster.bingemate_workspace.prod.bingemate-web

github <- snyk
