title: |md
  # Binge Mate Services
| {near: top-center}

user: Utilisateur {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F365-user.svg
}

admin: Administrateur {
  shape: image
  icon: https://cdn0.iconfinder.com/data/icons/business-startup-10/50/76-512.png
}


kubernetes_cluster: Kubernetes Cluster {
  icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg


  api_manager: API Manager {
      icon: https://avatars.githubusercontent.com/u/12655666?s=200&v=4
    
    api_gateway: API Gateway {
      shape: image
      icon: https://cdn1.iconfinder.com/data/icons/carbon-design-system-vol-4/32/gateway--api-512.png
    }

    admin_api: Admin API {
      shape: image
      icon: https://cdn1.iconfinder.com/data/icons/carbon-design-system-vol-2/32/api-512.png
    }

    portail: Portail {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/audit-3/512/18_Analysis_Report_Data_Web_Portal_Computing-512.png
    }

    console: Console {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/feather-5/24/terminal-512.png
    }

    mongo: MongoDB {
      shape: image
      icon: https://icons.terrastruct.com/dev%2Fmongodb.svg
    }

    elasticsearch: Elasticsearch {
      shape: image
      icon: https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/elasticsearch-512.png
    }

    api_gateway -> mongo
    api_gateway -> Elasticsearch
    admin_api -> mongo
    admin_api -> Elasticsearch
    portail -> mongo
    console -> admin_api
  }


  system: System WorkSpace {
    rancher: Rancher Stack {
      icon: https://media.trustradius.com/product-logos/pJ/jl/0QRDLLI2NBM6.PNG
      shape: image
    }

    rancher_console: Rancher Console {
      shape: image
      icon: https://cdn3.iconfinder.com/data/icons/feather-5/24/terminal-512.png
    }

    service_mesh: Service Mesh {
      istio: Istio Stack {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Istio-bluelogo-nobackground-unframed.svg/1365px-Istio-bluelogo-nobackground-unframed.svg.png
        shape: image
      }
    }

    devops: DevOps {

      argocd: ArgoCD Stack {
        icon: https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png
        shape: image
      }
    }

    monitoring: Monitoring {
      grafana: {
        shape: image
        icon: https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/grafana-512.png
      }
      
      prometheus: Prometheus Operator {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1200px-Prometheus_software_logo.svg.png
        shape: image
      }
      kube_state_metrics: Kube State Metrics {
        icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
        shape: image
      }
      node_exporter: Node Exporter {
        icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
        shape: image
      }
      alertmanager: Alert Manager {
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1200px-Prometheus_software_logo.svg.png
        shape: image
      }
      grafana -> prometheus
      kube_state_metrics -> prometheus
      node_exporter -> prometheus
      grafana <- alertmanager  
    }
  }

  bingemate_workspace: Binge Mate WorkSpace {

    icon: https://www.freepnglogos.com/uploads/coffee-logo-png/coffee-logo-design-creative-idea-logo-elements-2.png

    prod: Production Platform {
      bingemate_db: BDD {
        shape: cylinder
      }

      bingemate_api: Backend service

      bingemate_web: Frontend

      bingemate_api -> bingemate_db
    }

    dev: Development Platform {
      bingemate_db: BDD {
        shape: cylinder
      }

      bingemate_api: Backend service

      bingemate_web: Frontend

      bingemate_api -> bingemate_db
    }
  }

  system.devops.argocd -> bingemate_workspace
  system.service_mesh.istio -> bingemate_workspace

  api_manager.api_gateway -> bingemate_workspace.prod.bingemate_api
  api_manager.api_gateway -> bingemate_workspace.dev.bingemate_api
}

registry: Scaleway Registry {
  icon: https://cdn.icon-icons.com/icons2/2407/PNG/512/scaleway_icon_146103.png
  #shape: image
}

github: Github {
  icon: https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-social-github-512.png
  #shape: image
}

kubernetes_cluster -> registry
kubernetes_cluster.system.devops.argocd -> github
github -> registry

admin -> kubernetes_cluster.api_manager.console
admin -> kubernetes_cluster.system.rancher_console
admin -> kubernetes_cluster.system.monitoring.grafana
admin -> kubernetes_cluster.system.devops.argocd

user -> kubernetes_cluster.api_manager.portail
user -> kubernetes_cluster.api_manager.api_gateway
