title: |md
   # Indexing Media Files
| {near: top-center}

direction: right

step_scan: Scanning Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/fairy-tale/sage.png"
  }

  upload_dir: Upload Directory {
    shape: page
  }

  step: |md
    - Scan for new files
    - Check if is a media file
    - ...
  |
}

step_process_metadata: Metadata Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/projects/with-C-book.png"
  }

  tmdb: TMDB API {
    icon: "https://pbs.twimg.com/profile_images/1243623122089041920/gVZIvphd_400x400.jpg"
  }

  step: |md
    - Sanitize filename
    - Fetch metadata from TMDB
    -...
  |
}

step_process_transcoding: Transcoding Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/science/power-to-the-masses.png"
  }

  ffmpeg: FFmpeg {
    icon: "https://seeklogo.com/images/F/ffmpeg-logo-302A0FAEB4-seeklogo.com.png"
  }

  upload_dir: Upload Directory {
    shape: page
  }

  hls_dir: HLS Directory {
    shape: page
    content: |md
      - audio_1.m3u8
      - audio_1_001.ts
      - ...
      - audio_x_xxx.ts
      - video.m3u8
      - video_001.ts
      - ...
      - video_xxx.ts
      - subtitle_1.vtt
      - subtitle_2.vtt
      - ...
    |
  }

  step: |md
    - Analyze media file
    - Adjust transcode settings
    - Add intro video
    - Transcode media file to HLS
    -...
  |
}

step_index_in_db: Indexing Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/science/scientist.png"
  }

  db: Database {
    icon: "https://seeklogo.com/images/P/postgresql-logo-5309879B58-seeklogo.com.png"
  }

  step: |md
    - Add metadata to database
    - Set media file as available
    - ...
  |
}

step_upload_to_s3: Upload Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/science/rocket.png"
  }

  hls_dir: HLS Directory {
    shape: page
  }

  s3: S3 {
    icon: "https://cdn2.iconfinder.com/data/icons/amazon-aws-stencils/100/Storage__Content_Delivery_Amazon_S3_Bucket_with_Objects-256.png"
  }

  step: |md
    - Upload HLS files to S3
    - Upload metadata to S3
    -...
  |
}

step_cleanup: Cleanup Step {
  media_indexer: Media Indexer {
    icon: "https://github.com/egonelbre/gophers/raw/master/.thumb/vector/computer/gamer.png"
  }
  upload_dir: Upload Directory {
    shape: page
  }
  hls_dir: HLS Directory {
    shape: page
  }

  step: |md
    - Remove media file
    - Remove HLS files
    -...
  |
}

ffmpeg_command: FFmpeg Command {
    code: |go
    /usr/bin/ffmpeg -i /home/nospy/Projets/bingemate/media-indexer/assets/intro.mkv                          
    -i /home/nospy/Téléchargements/movies-source/Star Wars - Episode IV - A New Hope - 1977.mkv 
    -filter_complex [0:v:0]scale=1280:720,format=yuv420p,setsar=sar=1/1[v0]; 
    [1:v:0]scale=1280:720,format=yuv420p,setsar=sar=1/1[v1]; 
    [v0][v1]concat=n=2:v=1[outv] -map [outv] 
    -c:v libx264 -profile:v high -preset veryfast -crf 23 -pix_fmt yuv420p 
    -hls_time 15 -hls_playlist_type vod -hls_segment_filename 
    /home/nospy/Téléchargements/media-target/123456/segment_%03d.ts -hls_flags delete_segments 
    -f hls /home/nospy/Téléchargements/media-target/123456/index.m3u8

    /usr/bin/ffmpeg -i /app/assets/intro.mkv 
    -i /app/movies-source/One.Ranger.2023..mkv 
    -filter_complex [0:a:0][1:1]concat=n=2:v=0:a=1[outa] 
    -map [outa] -c:a aac -b:a 160k -ac 2 -hls_time 15 -hls_playlist_type vod 
    -hls_segment_filename /app/media-target/movies/1093994/audio_1_%03d.ts 
    /app/media-target/movies/1093994/audio_1.m3u8
    |
}

step_scan -> step_process_metadata -> step_process_transcoding -> step_upload_to_s3 -> step_cleanup -> step_index_in_db
step_process_transcoding -> ffmpeg_command
